### ISSUE TITLE
Understand geo data visualization

### ISSUE THREAD

**Issue by Codeinator-0711** [Team-Earth-Quake-Detector/team_1_earth_quake_detector#17]
How can we visualize geo data?

**Comment by karinahasler** [comment]
Geo data could be visualized through a heat map. Good explanation found here:

https://medium.com/@lyric09220/how-to-create-a-cool-seismic-heat-map-with-20-lines-of-python-code-e9b4bd9bc0b2

**Comment by karinahasler** [comment]
Hey coding people,
here's the current status. There is an OpenStreetMap with circle markers for all earthquakes of the last 24 hours that vary in size and color according to the earthquake's magnitude. There is an additional layer in order to show or hide the tectonic plates.

<img width="1030" alt="Bildschirmfoto 2021-05-19 um 17 43 59" src="https://user-images.githubusercontent.com/83064981/118843151-116a0f00-b8ca-11eb-93d3-482b956bcc88.png">

Go team!!

**Comment by Codeinator-0711** [comment]
Looks really cool. Good idea with the tectonic plates. Keep going Karina 💯
